services:
  - postgresql
addons:
  postgresql: "9.5"
  apt:
    packages:
      - postgresql-server-dev-9.5
script:
  - sudo make install
  - PGUSER=postgres make installcheck --debug=a
  - cat regression.diffs
