services:
  - postgresql
addons:
  postgresql: "9.5"
  apt:
    packages:
      - postgresql-server-dev-9.5

before_script:
  - sudo make install
  - psql -c 'CREATE EXTENSION lunardate;' -U postgres

script:
  - make PGUSER=postgres installcheck
  - cat regression.diffs
